# Generated by Django 2.1.5 on 2019-01-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='post-slug'),
        ),
    ]
